# Generated by Django 6.0.2 on 2026-02-18 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('not_applied', '未応募'), ('document', '書類選考'), ('test', 'Webテスト'), ('first', '一次面接'), ('second', '二次面接'), ('final', '最終面接'), ('offer', '内定'), ('closed', '見送り')], default='not_applied', max_length=30)),
                ('priority', models.PositiveSmallIntegerField(default=3)),
                ('url', models.URLField(blank=True)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
