# Generated by Django 6.0.2 on 2026-02-28 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('junior', '中学受験'), ('high', '高校受験'), ('university', '大学受験')], max_length=20)),
                ('school_type', models.CharField(blank=True, choices=[('national', '国立'), ('public', '公立'), ('private', '私立')], max_length=20)),
                ('deviation_value', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='偏差値')),
                ('status', models.CharField(choices=[('interested', '志望中'), ('plan_to_apply', '出願予定'), ('applied', '出願済'), ('exam_done', '受験済'), ('passed', '合格'), ('failed', '不合格')], default='interested', max_length=20)),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='受験日')),
                ('url', models.URLField(blank=True)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
