# Generated by Django 6.0.2 on 2026-03-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='motivation',
            field=models.TextField(blank=True, verbose_name='志望動機'),
        ),
        migrations.AddField(
            model_name='company',
            name='resume_memo',
            field=models.TextField(blank=True, verbose_name='コピペ用メモ'),
        ),
        migrations.AddField(
            model_name='company',
            name='self_pr',
            field=models.TextField(blank=True, verbose_name='自己PR'),
        ),
    ]
