# Generated by Django 6.0.2 on 2026-03-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_motivation_company_resume_memo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='entry_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='ES提出締切'),
        ),
        migrations.AddField(
            model_name='company',
            name='es_submitted',
            field=models.BooleanField(default=False, verbose_name='ES提出済み'),
        ),
        migrations.AddField(
            model_name='company',
            name='es_submitted_at',
            field=models.DateField(blank=True, null=True, verbose_name='ES提出日'),
        ),
        migrations.AddField(
            model_name='company',
            name='es_version_note',
            field=models.TextField(blank=True, verbose_name='提出バージョンメモ'),
        ),
        migrations.AddField(
            model_name='company',
            name='questions_asked',
            field=models.TextField(blank=True, verbose_name='面接で聞かれたこと'),
        ),
    ]
