# Generated by Django 6.0.2 on 2026-02-28 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_school'),
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('mock', '模試'), ('deadline', '出願締切'), ('exam', '入試'), ('interview', '面談'), ('result', '合格発表'), ('other', 'その他')], default='exam', max_length=20)),
                ('scheduled_at', models.DateTimeField(verbose_name='日時')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='場所')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_events', to='companies.school')),
            ],
        ),
    ]
