# Generated by Django 6.0.2 on 2026-02-28 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_school'),
        ('interviews', '0002_examevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('japanese', '国語'), ('math', '数学'), ('english', '英語'), ('science', '理科'), ('social', '社会'), ('essay', '小論文'), ('interview', '面接対策'), ('other', 'その他')], max_length=20, verbose_name='科目')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('study_date', models.DateField(verbose_name='学習日')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='勉強時間（分）')),
                ('material', models.CharField(blank=True, max_length=200, verbose_name='教材')),
                ('content', models.TextField(blank=True, verbose_name='学習内容')),
                ('next_action', models.TextField(blank=True, verbose_name='次にやること')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_logs', to='companies.school')),
            ],
        ),
    ]
